In [1]:
import numpy as np
import pandas as pd

#### read_csv()----> this function read the content from the csv file in pandas so that we can perform the operations on the data or we can perform effective analysis

In [2]:
you_data=pd.read_csv('youtube.csv')

In [3]:
you_data

,Title,channel_title,published_at,category_id,view_count,like_count,comment_count,favorite_count,duration,definition,caption,engagement_rate,likes_to_views_ratio,comments_to_views_ratio,duration_seconds,video_age_days
0,LA PERVERSA X LA INSUPERABLE X ALOFOKE MUSIC X...,AlofokeMusicSounds,2025-11-16 15:34:55+00:00,10,1405647,140463,9063,0,PT1M51S,hd,False,0.106375,0.099928,0.006448,111,1
1,Moana | Official Teaser,Disney,2025-11-17 17:00:47+00:00,24,2776847,26801,6684,0,PT1M,hd,True,0.012059,0.009652,0.002407,60,0
2,$0 - $1 Trillion Only FISHING in Steal a Brain...,CaylusBlox,2025-11-17 22:57:14+00:00,20,1189857,16174,1827,0,PT18M2S,hd,False,0.015129,0.013593,0.001535,1082,0
3,ALLDAY PROJECT - ‘ONE MORE TIME’ M/V,THEBLACKLABEL,2025-11-17 09:00:07+00:00,10,5319161,0,12869,0,PT3M23S,hd,True,0.002419,0.000000,0.002419,203,1
4,La Lupa | Vendetta Hero Trailer | Overwatch 2,PlayOverwatch,2025-11-17 17:00:06+00:00,20,597542,41742,4728,0,PT3M35S,hd,True,0.077768,0.069856,0.007912,215,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,Ghost of Yotei - Before You Buy,gameranx,2025-09-25 21:41:42+00:00,20,1366391,45978,9598,0,PT13M16S,hd,True,0.040674,0.033649,0.007024,796,53
533,"₹50,000 PS5 vs ₹2000 Game Stick 😲🤯 Who is the ...",Digidoty,2024-11-08 11:49:56+00:00,28,1576718,32917,327,0,PT46S,hd,False,0.021084,0.020877,0.000207,46,374
534,Arc Raiders - Before You Buy,gameranx,2025-10-31 21:57:47+00:00,20,1218921,28356,3146,0,PT14M14S,hd,True,0.025844,0.023263,0.002581,854,17
535,Clair Obscur: Expedition 33 Review,IGN,2025-04-23 09:00:23+00:00,20,1220485,16187,2947,0,PT17M48S,hd,False,0.015677,0.013263,0.002415,1068,209
536,Must Play Mobile Game-Epic War!😎 #shorts #game...,MohanadPC,2025-08-24 16:00:39+00:00,20,2157893,7439,12,0,PT32S,hd,False,0.003453,0.003447,0.000006,32,85

#### DataFrame--> Combination of multiple series(Column)

#### Squeeze--->squeeze parameter make sure that the data is in series format

In [5]:
type(you_data)

pandas.DataFrame

In [17]:
sqeeze_Fun=pd.read_csv('youtube_one_column.csv').squeeze('columns')

In [18]:
type(sqeeze_Fun)

pandas.Series

#### index_col for two column csv files

In [13]:
two_column=pd.read_csv('youtube_two_column.csv', index_col='Title').squeeze('columns')

In [14]:
type(two_column)

pandas.Series

In [19]:
two_column

Title
LA PERVERSA X LA INSUPERABLE X ALOFOKE MUSIC X SHADOW BLOW - BANDIDA    AlofokeMusicSounds
Moana | Official Teaser                                                             Disney
$0 - $1 Trillion Only FISHING in Steal a Brainrot..                             CaylusBlox
ALLDAY PROJECT - ‘ONE MORE TIME’ M/V                                         THEBLACKLABEL
La Lupa | Vendetta Hero Trailer | Overwatch 2                                PlayOverwatch
                                                                               ...
Ghost of Yotei - Before You Buy                                                   gameranx
₹50,000 PS5 vs ₹2000 Game Stick 😲🤯 Who is the Real Winner ?? #shorts              Digidoty
Arc Raiders - Before You Buy                                                      gameranx
Clair Obscur: Expedition 33 Review                                                     IGN
Must Play Mobile Game-Epic War!😎 #shorts #gamereviews                            MohanadPC
Name: channel_title, Length: 537, dtype: str

#### .values --> representing only the values of the given series
#### .index---> return only the index values from the given column
#### .dtype ---> provide the idea about the data type storing the values
#### .size---->provide the idea about total rows inside the data set
#### shape -->this attribute provide the  idea about the rows and colums information
#### ndim---> this attribute provide the idea about the dimension of the given dataset
#### name---> this attribute provide the idea about the name of the series
#### is_unique----> provides the idea about  weather the given column have the unique values or not

In [21]:
two_column.values

<ArrowStringArray>
['AlofokeMusicSounds',             'Disney',         'CaylusBlox',
      'THEBLACKLABEL',      'PlayOverwatch',             'CaseOh',
         'Charli xcx',            'Netflix',       'Asmongold TV',
 'Official DeeBabyTV',
 ...
          'MagicMush',           'gameranx',        'Dino Review',
     'SsethTzeentach',           'gameranx',           'gameranx',
           'Digidoty',           'gameranx',                'IGN',
          'MohanadPC']
Length: 537, dtype: str

In [22]:
two_column

Title
LA PERVERSA X LA INSUPERABLE X ALOFOKE MUSIC X SHADOW BLOW - BANDIDA    AlofokeMusicSounds
Moana | Official Teaser                                                             Disney
$0 - $1 Trillion Only FISHING in Steal a Brainrot..                             CaylusBlox
ALLDAY PROJECT - ‘ONE MORE TIME’ M/V                                         THEBLACKLABEL
La Lupa | Vendetta Hero Trailer | Overwatch 2                                PlayOverwatch
                                                                               ...
Ghost of Yotei - Before You Buy                                                   gameranx
₹50,000 PS5 vs ₹2000 Game Stick 😲🤯 Who is the Real Winner ?? #shorts              Digidoty
Arc Raiders - Before You Buy                                                      gameranx
Clair Obscur: Expedition 33 Review                                                     IGN
Must Play Mobile Game-Epic War!😎 #shorts #gamereviews                            MohanadPC
Name: channel_title, Length: 537, dtype: str

In [26]:
sqeeze_Fun.index

RangeIndex(start=0, stop=537, step=1)

In [27]:
sqeeze_Fun.dtype

In [28]:
two_column.dtype

In [29]:
you_data.dtypes

Title                          str
channel_title                  str
published_at                   str
category_id                  int64
view_count                   int64
like_count                   int64
comment_count                int64
favorite_count               int64
duration                       str
definition                     str
caption                       bool
engagement_rate            float64
likes_to_views_ratio       float64
comments_to_views_ratio    float64
duration_seconds             int64
video_age_days               int64
dtype: object

In [30]:
you_data.shape

(537, 16)

In [31]:
two_column.shape

(537,)

In [32]:
two_column.ndim

1

In [33]:
you_data.ndim

2

In [34]:
you_data.category_id.name

'category_id'

In [35]:
you_data.category_id.is_unique

False

## Series methods

#### 1. head()--->provide the top preview of data as the 5 rows of the dataframe or series, it is quite helpfil with providing the preview of the datset and if we want to preview top 10 rows then we can pass 10 as a argument or for 7 rows we can pass 7 as argument

In [36]:
you_data.category_id.head()

0    10
1    24
2    20
3    10
4    20
Name: category_id, dtype: int64

In [37]:
you_data.category_id.head(10)

0    10
1    24
2    20
3    10
4    20
5    20
6    10
7    24
8    20
9    10
Name: category_id, dtype: int64

In [38]:
you_data.head()

,Title,channel_title,published_at,category_id,view_count,like_count,comment_count,favorite_count,duration,definition,caption,engagement_rate,likes_to_views_ratio,comments_to_views_ratio,duration_seconds,video_age_days
0,LA PERVERSA X LA INSUPERABLE X ALOFOKE MUSIC X...,AlofokeMusicSounds,2025-11-16 15:34:55+00:00,10,1405647,140463,9063,0,PT1M51S,hd,False,0.106375,0.099928,0.006448,111,1
1,Moana | Official Teaser,Disney,2025-11-17 17:00:47+00:00,24,2776847,26801,6684,0,PT1M,hd,True,0.012059,0.009652,0.002407,60,0
2,$0 - $1 Trillion Only FISHING in Steal a Brain...,CaylusBlox,2025-11-17 22:57:14+00:00,20,1189857,16174,1827,0,PT18M2S,hd,False,0.015129,0.013593,0.001535,1082,0
3,ALLDAY PROJECT - ‘ONE MORE TIME’ M/V,THEBLACKLABEL,2025-11-17 09:00:07+00:00,10,5319161,0,12869,0,PT3M23S,hd,True,0.002419,0.000000,0.002419,203,1
4,La Lupa | Vendetta Hero Trailer | Overwatch 2,PlayOverwatch,2025-11-17 17:00:06+00:00,20,597542,41742,4728,0,PT3M35S,hd,True,0.077768,0.069856,0.007912,215,0

#### 2. tail()--- it provide the bottom preview of data as the bottom 5 rows. for eg.. dataset ---> salary column---top 5 rows---salary---7 lpa---->top 10---> top 15 ,,, with tail() bottom 5 rows---salary---4 lpa

In [39]:
you_data.category_id.tail(10)

527    20
528    20
529    20
530    20
531    20
532    20
533    28
534    20
535    20
536    20
Name: category_id, dtype: int64

#### 3. sample()--->provide any custom row from the dataset for us to preview it, it provide any random values

In [41]:
you_data.sample(5)

,Title,channel_title,published_at,category_id,view_count,like_count,comment_count,favorite_count,duration,definition,caption,engagement_rate,likes_to_views_ratio,comments_to_views_ratio,duration_seconds,video_age_days
323,Ayeein 😂😂ye kaise hua???? #food #cookingrecipe...,Secret of yum,2023-12-05 10:51:19+00:00,22,38266664,1427982,1886,0,PT59S,hd,False,0.037366,0.037317,0.000049,59,713
68,Machine Learning Full Course - Learn Machine L...,edureka!,2019-09-22 08:30:00+00:00,27,3517098,61981,1346,0,PT9H38M32S,hd,True,0.018005,0.017623,0.000383,34712,2249
58,AI Learns Insane Way to Jump,AI Warehouse,2024-03-25 22:08:29+00:00,24,7108310,281551,1396,0,PT50S,hd,True,0.039805,0.039609,0.000196,50,602
8,It's all crashing down..,Asmongold TV,2025-11-18 02:00:35+00:00,20,755718,26231,5285,0,PT17M13S,hd,False,0.041703,0.034710,0.006993,1033,0
179,Data Engineer vs. Data Scientist ft. @eczachly_,Sundas Khalid,2024-11-18 15:08:49+00:00,28,1552154,39747,405,0,PT53S,hd,False,0.025869,0.025608,0.000261,53,364

#### 4. value_counts()---> it provide the idea about the count of the values(categorical values),

In [44]:
you_data.category_id.value_counts()

category_id
27    150
22     99
20     57
24     54
10     51
26     47
28     36
17     15
1      10
19      8
23      6
25      4
Name: count, dtype: int64

In [45]:
type(you_data)

pandas.DataFrame

In [46]:
type(you_data.category_id)

pandas.Series

#### 5. sort_values()---> this method sorts the values in an ascending manner. it can be useful for us for the numerical column. you can even sort the value in descending manner also, fpr descending pass the ascending =false inside the method

In [47]:
you_data.category_id.sort_values()

43      1
49      1
105     1
467     1
254     1
       ..
221    28
228    28
257    28
520    28
533    28
Name: category_id, Length: 537, dtype: int64

In [48]:
you_data.category_id.sort_values(ascending=False)

520    28
533    28
511    28
274    28
280    28
       ..
105     1
43      1
467     1
19      1
22      1
Name: category_id, Length: 537, dtype: int64

#### Method chaining---> we will use multiple method together to get the required values in a way first method output will be second method input and 2nd method output will be the 3rd method input

In [50]:
you_data.category_id.sort_values(ascending=False).head(1)

520    28
Name: category_id, dtype: int64

In [51]:
you_data.category_id.sort_values(ascending=False).head(1).values[0]

np.int64(28)

#### inplace---> in order to make a change in our data permanent

In [55]:
you_data.category_id.sort_values(inplace=True)

In [56]:
you_data.category_id

0      10
1      24
2      20
3      10
4      20
       ..
532    20
533    28
534    20
535    20
536    20
Name: category_id, Length: 537, dtype: int64

#### sort_index()---> this method sort the index of dataset

In [54]:
you_data.category_id.sort_index()

0      10
1      24
2      20
3      10
4      20
       ..
532    20
533    28
534    20
535    20
536    20
Name: category_id, Length: 537, dtype: int64

In [57]:
two_column.sort_index()

Title
"Godfather of AI" Geoffrey Hinton: The 60 Minutes Interview                                                            60 Minutes
"what song is this again?" Charlie Puth making Birds Of A Feather out of "nothing"  | June 27, 2024    Charlie Puth Daily Updates
#0 Python for Beginners | Programming Tutorial                                                                            Telusko
#09 Time to say Goodbye to the family | Back to Kerala🏝 #chuttidays                                                therainbowgirl
#146 Dinner and Breakfast in Rajdhani Express                                                                      therainbowgirl
                                                                                                                  ...
일주일만에 뱃살 빼기🔥30분 서서하는 복근 운동 - 스쿼트X 런지X 점핑X                                                                                    MIZI
🇮🇹 Italy’s AI Athlete – Pure Style, Pure Power  #robot #humanoid #Future  #Olympics #aiart                               VS SEVEN
🍞💛 Rasmalai Bread Recipe | Instant Indian Dessert 🤯                                                              The Flavor Queen
👩‍💻 Python for Beginners Tutorial                                                                                 Kevin Stratvert
🔴 LIVE! - WINNING in SOLO FORTNITE SIMPSONS!                                                                        Typical Gamer
Name: channel_title, Length: 537, dtype: str

In [58]:
you_data.category_id.sum()

np.int64(12059)